import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import Footer from './components/footer';
import Navbar from './components/navbar/navbar';
import './globals.css';

import clsx from 'clsx';
import Wave from './components/background-decorations/wave';
import DotGrid from './components/background-decorations/dot-grid';
import LightSpot from './components/background-decorations/light-spot';

const inter = Lato({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Navbar />
				<Wave />
				<DotGrid height={1} className='max-xl:top-[550px] xl:top-[787px] left-0 max-md:invisible' />
				<DotGrid height={2} className='top-[145px] right-0' />
				<div className='container mx-auto px-4 max-w-screen-xl min-h-screen'>
					<LightSpot className='transform translate-x-[-250px] translate-y-[-200px] -z-50 max-md:w-0 max-md:h-0' />

					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
