import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import Footer from './components/footer';
import Navbar from './components/navbar/navbar';
import './globals.css';
import GlobalDecorations from './components/background-decorations/global-decorations';
import clsx from 'clsx';

const inter = Lato({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={clsx(inter.className, 'min-h-screen')}>
				<Navbar />
				<div className='container mx-auto px-4 max-w-screen-xl'>
					<GlobalDecorations />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
