name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Format with Prettier
        run: pnpm run format:write
      - name: Migrate Biome config
        run: pnpm exec biome migrate --write
      - name: Format with Biome
        run: pnpm run lint:fix
      - name: Run autofix.ci
        uses: autofix-ci/action@v1
        with:
          commit-message: 'style: apply automatic fixes'
